# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Gustav\Desktop\Projektkurs\Code\src\pythion\_layout\action.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Action(object):
    def setupUi(self, Action):
        Action.setObjectName("Action")
        Action.resize(142, 42)
        self.button = QtWidgets.QPushButton(Action)
        self.button.setGeometry(QtCore.QRect(10, 10, 121, 21))
        self.button.setObjectName("button")

        self.retranslateUi(Action)
        QtCore.QMetaObject.connectSlotsByName(Action)

    def retranslateUi(self, Action):
        _translate = QtCore.QCoreApplication.translate
        Action.setWindowTitle(_translate("Action", "Input Device"))
        self.button.setText(_translate("Action", "PushButton"))
