# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Gustav\Desktop\Projektkurs\Code\src\pythion\_gui\layout\output.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Output(object):
    def setupUi(self, Output):
        Output.setObjectName("Output")
        Output.resize(230, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Output.sizePolicy().hasHeightForWidth())
        Output.setSizePolicy(sizePolicy)
        Output.setMinimumSize(QtCore.QSize(230, 0))
        self.frame_2 = QtWidgets.QFrame(Output)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 211, 481))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 191, 461))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nameLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.nameLabel.setText("")
        self.nameLabel.setObjectName("nameLabel")
        self.verticalLayout.addWidget(self.nameLabel)
        self.lastValueLCD = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.lastValueLCD.setEnabled(False)
        self.lastValueLCD.setStyleSheet("color: #aaaaaa;")
        self.lastValueLCD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lastValueLCD.setProperty("value", 0.0)
        self.lastValueLCD.setProperty("intValue", 0)
        self.lastValueLCD.setObjectName("lastValueLCD")
        self.verticalLayout.addWidget(self.lastValueLCD)
        self.outputLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.outputLabel.setObjectName("outputLabel")
        self.verticalLayout.addWidget(self.outputLabel)
        self.outputDial = QtWidgets.QDial(self.verticalLayoutWidget)
        self.outputDial.setEnabled(False)
        self.outputDial.setMaximum(500)
        self.outputDial.setObjectName("outputDial")
        self.verticalLayout.addWidget(self.outputDial)
        self.outputSpinbox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.outputSpinbox.setEnabled(False)
        self.outputSpinbox.setObjectName("outputSpinbox")
        self.verticalLayout.addWidget(self.outputSpinbox)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.setBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.setBtn.setEnabled(False)
        self.setBtn.setMinimumSize(QtCore.QSize(0, 20))
        self.setBtn.setStyleSheet("")
        self.setBtn.setAutoDefault(False)
        self.setBtn.setDefault(False)
        self.setBtn.setFlat(False)
        self.setBtn.setObjectName("setBtn")
        self.verticalLayout.addWidget(self.setBtn)
        self.connectBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.connectBtn.setObjectName("connectBtn")
        self.verticalLayout.addWidget(self.connectBtn)
        self.zeroOnConnectBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zeroOnConnectBox.sizePolicy().hasHeightForWidth())
        self.zeroOnConnectBox.setSizePolicy(sizePolicy)
        self.zeroOnConnectBox.setObjectName("zeroOnConnectBox")
        self.verticalLayout.addWidget(self.zeroOnConnectBox)
        self.zeroOnDisconnectBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zeroOnDisconnectBox.sizePolicy().hasHeightForWidth())
        self.zeroOnDisconnectBox.setSizePolicy(sizePolicy)
        self.zeroOnDisconnectBox.setChecked(True)
        self.zeroOnDisconnectBox.setObjectName("zeroOnDisconnectBox")
        self.verticalLayout.addWidget(self.zeroOnDisconnectBox)

        self.retranslateUi(Output)
        QtCore.QMetaObject.connectSlotsByName(Output)

    def retranslateUi(self, Output):
        _translate = QtCore.QCoreApplication.translate
        Output.setWindowTitle(_translate("Output", "Output Device"))
        self.outputLabel.setText(_translate("Output", "(last set target value)"))
        self.label_3.setText(_translate("Output", "(new target value)"))
        self.setBtn.setText(_translate("Output", "Set value"))
        self.connectBtn.setText(_translate("Output", "Connect"))
        self.zeroOnConnectBox.setText(_translate("Output", "Set value to zero \n"
"on connect"))
        self.zeroOnDisconnectBox.setText(_translate("Output", "Set value to zero \n"
"on disconnect"))
