# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Gustav\Desktop\Projektkurs\Code\src\pythion\_gui\layout\plotframe.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlotFrame(object):
    def setupUi(self, PlotFrame):
        PlotFrame.setObjectName("PlotFrame")
        PlotFrame.resize(674, 468)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(PlotFrame.sizePolicy().hasHeightForWidth())
        PlotFrame.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(PlotFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.mainLayout = QtWidgets.QVBoxLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.gridLayout.addLayout(self.mainLayout, 0, 0, 1, 1)
        self.finishedLabel = QtWidgets.QLabel(PlotFrame)
        self.finishedLabel.setGeometry(QtCore.QRect(10, 60, 121, 16))
        self.finishedLabel.setStyleSheet("color: green;")
        self.finishedLabel.setText("")
        self.finishedLabel.setObjectName("finishedLabel")

        self.retranslateUi(PlotFrame)
        QtCore.QMetaObject.connectSlotsByName(PlotFrame)

    def retranslateUi(self, PlotFrame):
        _translate = QtCore.QCoreApplication.translate
        PlotFrame.setWindowTitle(_translate("PlotFrame", "Plot Frame"))
