# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\channel_params_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(370, 290)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 330, 40))
        self.label.setFrameShape(QtWidgets.QFrame.Panel)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setLineWidth(2)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setGeometry(QtCore.QRect(30, 80, 60, 29))
        self.spinBox.setObjectName("spinBox")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(110, 80, 120, 30))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 120, 140, 20))
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(30, 150, 130, 28))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(190, 150, 130, 28))
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(180, 120, 160, 20))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(200, 220, 110, 30))
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(30, 190, 141, 81))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "CHANNEL PARAMETERS CONFIG"))
        self.label_2.setText(_translate("Form", "Channel number"))
        self.label_3.setText(_translate("Form", "Channel parameters"))
        self.comboBox.setItemText(1, _translate("Form", "VSET"))
        self.comboBox.setItemText(2, _translate("Form", "VMON"))
        self.comboBox.setItemText(3, _translate("Form", "ISET"))
        self.comboBox.setItemText(4, _translate("Form", "IMON"))
        self.comboBox.setItemText(5, _translate("Form", "IMRANGE"))
        self.comboBox.setItemText(6, _translate("Form", "MAXV"))
        self.comboBox.setItemText(7, _translate("Form", "RUP"))
        self.comboBox.setItemText(8, _translate("Form", "RDW"))
        self.comboBox.setItemText(9, _translate("Form", "TRIP"))
        self.comboBox.setItemText(10, _translate("Form", "PDWN"))
        self.comboBox.setItemText(11, _translate("Form", "POL"))
        self.comboBox.setItemText(12, _translate("Form", "STAT"))
        self.label_4.setText(_translate("Form", "Value (no auto refresh)"))
        self.pushButton.setText(_translate("Form", "✅︎ Configure"))
