# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_caen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CAEN(object):
    def setupUi(self, CAEN):
        CAEN.setObjectName("CAEN")
        CAEN.resize(1000, 600)
        self.gridLayoutWidget = QtWidgets.QWidget(CAEN)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 981, 581))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.caen_grid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.caen_grid.setContentsMargins(0, 0, 0, 0)
        self.caen_grid.setObjectName("caen_grid")

        self.retranslateUi(CAEN)
        QtCore.QMetaObject.connectSlotsByName(CAEN)

    def retranslateUi(self, CAEN):
        _translate = QtCore.QCoreApplication.translate
        CAEN.setWindowTitle(_translate("CAEN", "Form"))
