from autogenerated.output_component import Ui_MainWindow
from PyQt5.QtWidgets import QApplication, QDialog, QMainWindow, QMessageBox

class Window(QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
        self.configure()

    def configure(self):
        # Connect dial to input voltage display
        self.voltageDial.valueChanged.connect(self.newValueLCD.display)
        self.setBtn.clicked.connect(self.set_value)
    
    def set_value(self):
        self.lastValueLCD.display(self.voltageDial.value())