from __future__ import annotations
from autogenerated.output_component import Ui_MainWindow
from PyQt5.QtWidgets import QApplication, QDialog, QMainWindow, QMessageBox
from interfaces.output import Output

class OutputComponent(QMainWindow, Ui_MainWindow):
    def __init__(self, interface: Output, parent=None):
        # Boilerplate initialization
        super().__init__(parent)
        self.setupUi(self)
        # Custom initialization
        self.interface = interface
        self.configure()

    def configure(self) -> None:
        if self.interface.has_feedback:
            raise NotImplementedError('Outputs with live feedback have not been implemented!')
        
        # Connect dial to input voltage display
        self.voltageDial.valueChanged.connect(self.newValueLCD.display)
        self.setBtn.clicked.connect(self.set_value)
    
    def set_value(self) -> None:
        val = self.voltageDial.value()
        self.interface.target = val
        self.lastValueLCD.display(val)